// Generated by CoffeeScript 1.9.3
(function() {
  var Schema, Station, StationSchema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  StationSchema = new Schema({
    count: Number
  });

  module.exports = mongoose.model('Station', StationSchema);

  Station = mongoose.model('Station', StationSchema);

}).call(this);
